name: prcheck
on:
  pull_request:
    types:
      - opened
      - reopened
    
jobs:
  prcheck:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Comment on PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          jq -nc '{"body": "test comment"}' | \
          curl -sL  -X POST -d @- \
            -H "Content-Type: application/json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/$GITHUB_REPOSITORY/commits/$GITHUB_SHA/comments"
